name: e2e

on:
  pull_request:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: echo '${{ toJSON(github) }}'

      - run: echo '${{ toJSON(job) }}'

      - run: echo '${{ toJSON(steps) }}'

      - run: echo '${{ toJSON(runner) }}'

      - run: echo '${{ toJSON(strategy) }}'

      - run: echo '${{ toJSON(matrix) }}'

      - run: env | sort

      - run: cat ${{ github.step_summary }}

      - run: cat $GITHUB_EVENT_PATH | jq

      - run: go build
