name: goreleaser

on:
  pull_request:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: ./

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: go build
